# This is the name of the workflow, visible on GitHub UI
name: linux

# Run on a Push or a Pull Request
on: [push, pull_request]

jobs:
  rubocop: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6

      # Install and run Arduino CI tests for rubocop
      - name: Build and Execute
        run: |
          g++ -v
          time bundle install
          time bundle exec rubocop --version
          time bundle exec rubocop -D .
          time bundle exec rspec --backtrace

  TestSomething: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6

      # Install and run Arduino CI tests for TestSomething
      - name: Build and Execute
        run: |
          g++ -v
          time bundle install
          cd SampleProjects/TestSomething
          time bundle install
          time bundle exec arduino_ci.rb --skip-examples-compilation
          time bundle exec arduino_ci.rb --skip-unittests

  NetworkLib: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with: 
          ruby-version: 2.6

      # Install and run Arduino CI tests for NetworkLib
      - name: Build and Execute
        run: |
          g++ -v
          time bundle install
          cd SampleProjects/NetworkLib
          ./scripts/install.sh
          time bundle install
          time bundle exec arduino_ci.rb --skip-examples-compilation
          time bundle exec arduino_ci.rb --skip-unittests
